language: go
go:
  - 1.2
  - 1.3
  - tip
branches:
  only:
    - master
install:
  - go install github.com/richardlehane/siegfried/cmd/sieg
script:
  - go test github.com/richardlehane/siegfried/cmd/sieg