language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.4.2
branches:
  only:
    - master
install:
  - go get github.com/richardlehane/siegfried/cmd/sf
script:
  - go test github.com/richardlehane/siegfried/cmd/sf
