language: go
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip
branches:
  only:
    - master
install:
  - go get github.com/richardlehane/siegfried/cmd/sf
script:
  - go test github.com/richardlehane/siegfried/cmd/sf
sudo: false
