language: go
go:
  - 1.2
  - tip
install: 
  - go get github.com/richardlehane/siegfried
script:
  - go test github.com/richardlehane/siegfried/pkg/core/bytematcher
  - go test github.com/richardlehane/siegfried/pkg/pronom
  - go test github.com/richardlehane/siegfried/cmd/siegfried