sudo: false
language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- tip
branches:
  except:
  - develop
install:
- go get github.com/richardlehane/siegfried/cmd/sf
script:
- go test github.com/richardlehane/siegfried/cmd/sf
before_deploy:
- go install -a -tags brew github.com/richardlehane/siegfried/cmd/sf
- go install -a -tags brew github.com/richardlehane/siegfried/cmd/roy
- chmod +x debbuilder.sh
- ./debbuilder.sh
deploy:
  on:
    tags: true
    go: 1.6
  provider: bintray
  file: ${HOME}/deb/bintray.json
  user: richardlehane
  skip_cleanup: true
  key:
    secure: oIwrI6pFk7Ji6axsDT/DeS04kPW+AuTL/UfXD+L4p4ie4g+LTw2g6HWJIo7CAdd3jtQdXFEah1O5wNtvggvwxkeTo5gOlIjzY3Lfi0MPezct6bu4wAJM16to2Osflub4UU78fT2jMxZjjdczgXF9ir0TS2FqKGB9eiLbDSwlfbmf4zbe1zK/iGfFgvO1ahfLXu47zgEGsYJrmcTyJ+euG/kAqU3j9Gr8lDu1znXs9wb1AbJNFSL7N+mnPGSJjyRU5E4tdK515XcEN1pChtPLRvPE3Z85PVbicUxgMGHbLP8xOerfcNT9FqvVAPvRSeKQuf4kbM0lljPFmtOkaf9egp65HCT8DiApOxnE9Zj+bSVydCanH1OQMupv9RJFIUuDKLNYEU/nvGUl2k8UMbFLoGzINVVsxS5AQDMQsxO+dQyuIkIJ/Iup0gOJ3SHhwh8Bdp9fLNxudljepPw6xTeUmLIQFUCYEf1MVbcXccq7vOM60KxL1JJK4RQ3KCO+afMJ+K0UUFw7Dj9SmfFAXgNN/mTeV11wRRODjClic1zjQgAq6Ik+bsV/dZYrSDsj3mncAlG8ZDmkMjZELQk+jCrPqJ6VilIShN5ky1TSiaeS8gnQDt39J2BszVVLGS87umvJgxV2FBHJw2JK8zAS/BGtp4y8M6UylHK3xETFXLYGZ38=
