language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
  - +3887950
branches:
  only:
    - master
install:
  - go get github.com/richardlehane/siegfried/cmd/sf
script:
  - go test github.com/richardlehane/siegfried/cmd/sf