version: "{build}"

environment:
  GOPATH: c:\gopath

platform:
  - x86
  - x64

#branches:
#  only:
#    - master

clone_folder: c:\gopath\src\github.com\richardlehane\siegfried

build_script:
  - go install -a github.com/richardlehane/siegfried/cmd/sf
  - go install -a github.com/richardlehane/siegfried/cmd/roy
  - ps: $env:SFVERSION="_"
  - ps: if(test-path $env:APPVEYOR_REPO_TAG_NAME){$env:SFVERSION=$env:APPVEYOR_REPO_TAG_NAME.Trim("v").Replace(".","-")}
  - ps: if($env:PLATFORM -eq "x64"){$env:WINTYPE="win64"}
  - ps: if($env:PLATFORM -eq "x86"){$env:WINTYPE="win32"}

after_build:
  7z a siegfried_%SFVERSION%_%WINTYPE%.zip c:\gopath\bin\*.exe

artifacts:
  - path: siegfried_$(SFVERSION)_$(WINTYPE).zip
    name: siegfried_$(SFVERSION)_$(WINTYPE)

deploy:
  - provider: GitHub
    auth_token:
      secure: d/jFwo/lO0o59JZDJdkA7E3NgHvknKz9aSMz4gRLMLZ6CiWJOGOA3mDYuAtCAEPo
    release: $(APPVEYOR_REPO_TAG_NAME) 
    description: 'Release description goes here'
    artifact: siegfried_$(SFVERSION)_$(WINTYPE)      
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true
      #branch: master               