version: "{build}"

environment:
  GOPATH: c:\gopath

platform:
  - x86
  - x64

#branches:
#  only:
#    - master

clone_folder: c:\gopath\src\github.com\richardlehane\siegfried

build_script:
  - go install -a github.com/richardlehane/siegfried/cmd/sf
  - go install -a github.com/richardlehane/siegfried/cmd/roy

artifacts:
  - path: '**\bin'
    name: siegfried_$(APPVEYOR_REPO_TAG_NAME)_win{platform}

deploy:
  - provider: GitHub
    auth_token:
      secure: d/jFwo/lO0o59JZDJdkA7E3NgHvknKz9aSMz4gRLMLZ6CiWJOGOA3mDYuAtCAEPo
    release: $(APPVEYOR_REPO_TAG_NAME) 
    description: 'Release description goes here'
    artifact: siegfried_$(APPVEYOR_REPO_TAG_NAME)_win{platform}       
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
      #branch: master               